---
title: "Datenqualität GEIGER"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
```

Row {data-height=100}
-----------------------------------------------------------------------

### Aktualität der Tabelle

```{r Akutalität, echo=TRUE}
gauge(indicator,  min = 0, max = 100, symbol = '%',label = "Aktualität", gaugeSectors(
  success = c(96, 100), warning = c(90, 95), danger = c(0, 89)
))


```

Column {data-width=350}
-----------------------------------------------------------------------

### Vollständigkeit

```{r}
gauge(Fehlende,  min = 0, max = 100, symbol = '%',label = "Vollständig", gaugeSectors(
  success = c(96, 100), warning = c(90, 95), danger = c(0, 89)
))

```

### Ausreiser

```{r}
gauge(calcAusreiserInt,  min = 0, max = 100, symbol = '%',label = "Normalität", gaugeSectors(
  success = c(96, 100), warning = c(90, 95), danger = c(0, 89)
))
```
### Eindeutigkeit

```{r}
gauge(calcDoppelInt,  min = 0, max = 100, symbol = '%',label = "Eindeutigkeit", gaugeSectors(
  success = c(96, 100), warning = c(90, 95), danger = c(0, 89)
))


```

### Datenqualität

```{r}
gauge(finalInt,  min = 0, max = 100, symbol = '%', label = "Datenqualität", gaugeSectors(
  success = c(96, 100), warning = c(90, 95), danger = c(0, 89)
))


```
